### ISSUE TITLE
Menu not responsive?

### ISSUE THREAD

**Issue by oscon** [getgrav/grav-skeleton-pinpress-site#1]
Is there a responsive error in the theme PinPress?
Using a iPad in the portrait format, menu is shown directly in the content nearly invisible
(try http://demo.getgrav.org/pinpress-skeleton/ using http://ipadpeek.com/ in portrait mode)

**Comment by hexplor** [comment]
It actually display fine for me. Screenshot maybe ?

**Comment by oscon** [comment]
![2015-12-21 17_46_01-ipad peek _ iphone peek](https://cloud.githubusercontent.com/assets/478932/11935927/dd915d76-a80a-11e5-93c5-9b638ca39e50.jpg)

**Comment by hexplor** [comment]
ok, will try to work on that. Will let you know with possible fix.

**Comment by hexplor** [comment]
Ok. Please check if that fixed your issue: https://github.com/getgrav/grav-theme-pinpress/commit/d16a2f6111424b3e73412caaf101b258b3dafeb1

**Comment by oscon** [comment]
Thanks, works perfect now! 

Am 2015-12-22 10:53, schrieb Karol Orzeł: 

> Ok. Please check if that fixed your issue: getgrav/grav-theme-pinpress@d16a2f6 [1] 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].

## Links:

[1]
https://github.com/getgrav/grav-theme-pinpress/commit/d16a2f6111424b3e73412caaf101b258b3dafeb1
[2]
https://github.com/getgrav/grav-skeleton-pinpress-site/issues/1#issuecomment-166569943
