### ISSUE TITLE
How to edit social link in sidebar

### ISSUE THREAD

**Issue by MarieComet** [getgrav/grav-skeleton-pinpress-site#4]
Hi, 
Can you tell me how to edit social links in the sidebar ?
I found the "sidebar" page, but no options to edit the links.

Thanks you.

**Comment by trezcan** [comment]
You can add your profile links (and remove ones you don't use) on `/user/pages/sidebar/about/about.md`

**Comment by MarieComet** [comment]
Hi @trezcan thanks for your answer ! 🎉
